---
- hosts: dev
  user: root
  tasks:
    - name: install epel
      action: command creates=/etc/yum.repos.d/epel.repo rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

    - name: install postgres repository
      action: command rpm -Uvh --replacepkgs http://yum.postgresql.org/9.2/redhat/rhel-6-x86_64/pgdg-redhat92-9.2-7.noarch.rpm

    - name: make sure packages are installed
      action: yum pkg={{item}} state=installed
      with_items:
        - htop
        - atool
        - rubygems
        - python-virtualenv
        - python-setuptools
        - git
        - python-devel
        - ruby-devel
        - postgresql92-libs
        - postgresql92-devel
        - libxml2-devel
        - libxslt-devel
        - postgresql92
        - rpmdevtools
        - gcc
        - gcc-c++
        - make
        - bison
        - httpd
        - createrepo
        - mod_wsgi
        - java-openjdk
        - tomcat6
        - cronie
        - libselinux-python
        - wget
        - vim
        - python-psycopg2


#SOLR setup
    - name: prepare packages needed for solr
      action: yum pkg={{item}} state=installed
      with_items:
        - tomcat6
        - tomcat6-webapps
        - tomcat6-admin-webapps
        - wget
        - java-openjdk
        - libselinux-python

    - name: enabling tomcat service
      command: chkconfig tomcat6 on

    - name: starting tomcat service
      command: service tomcat6 start

    - name: Download Common Logging 1.1.3
      get_url: url="http://apache.org/dist/commons/logging/binaries/commons-logging-1.1.3-bin.tar.gz" dest="~/" force=no
#      shell: creates=~/commons-logging-1.1.3-bin.tar.gz "cd  ~/ && wget http://apache.cc.uoc.gr/commons/logging/binaries/commons-logging-1.1.3-bin.tar.gz"


    - name: Unpack common-logging
      shell: "cd ~/ && tar -zxvf commons-logging-1.1.3-bin.tar.gz && cd commons-logging-1.1.3 && cp commons-logging-*.jar /usr/share/tomcat6/lib/"

    - name: Download slf4j 1.7.5
      #get_url: url="http://www.slf4j.org/dist/slf4j-1.7.5.tar.gz" dest="~/" force=no 
      command: creates=~/slf4j-1.7.5.tar.gz chdir=~/ wget -T 40  http://www.slf4j.org/dist/slf4j-1.7.5.tar.gz

    - name: Unpack slf4j
      shell: "cd ~/ && tar -zxvf slf4j-1.7.5.tar.gz && cd slf4j-1.7.5 && cp slf4j-*.jar /usr/share/tomcat6/lib/"

    - name: Download solr 4.2.1
      #get_url: url="http://archive.apache.org/dist/lucene/solr/4.2.1/solr-4.2.1.tgz" dest="~/" force=no
      #shell: creates=~/solr-4.2.1.tgz "cd  ~/ && wget -T 40 http://archive.apache.org/dist/lucene/solr/4.2.1/solr-4.2.1.tgz"
      command: creates=~/solr-4.2.1.tgz chdir=~/ wget -T 40  http://archive.apache.org/dist/lucene/solr/4.2.1/solr-4.2.1.tgz

    - name: Unpack solr
      shell: "cd ~/ && tar -zxvf solr-4.2.1.tgz && cd solr-4.2.1/dist && cp solr-4.2.1.war /var/lib/tomcat6/webapps/solr.war"

    - name: Setup solr home folder
      shell: "mkdir -p /home/solr && cp -R ~/solr-4.2.1/example/solr/* /home/solr && cd /home/solr/collection1/conf/ && rm schema.xml && wget  --no-check-certificate https://raw.github.com/okfn/ckanext-geodatagov/master/solr/schema.xml && chown -R tomcat /home/solr"

    - name: restarting tomcat service
      action: service name=tomcat6 state=restarted



    - name: copy needed solr config file
      action: copy src=usr/share/tomcat6/webapps/solr/WEB-INF/web.xml dest=/usr/share/tomcat6/webapps/solr/WEB-INF/web.xml force=yes

    - name: restarting tomcat service
      action: service name=tomcat6 state=restarted
      #command: service tomcat6 restart

 
#
# install a new version of libxml - needs to be greater than 2.9 for spatial plugin
#
     
#    - name: install libxml 
#      action: command rpm -Uvh --replacepkgs ftp://xmlsoft.org/libxml2/libxml2-2.9.2-1.fc19.x86_64.rpm

    - name: Download libxml2-2.9.2
      command: creates=~/libxml2-2.9.2.tar.gz chdir=~/ wget -T 40  ftp://xmlsoft.org/libxml2/libxml2-2.9.2.tar.gz

    - name: unpack libxml2-2.9.2
      command: creates=~/libxml2-2.9.2/ chdir=~/ tar zxf libxml2-2.9.2.tar.gz

    - name: configure libxml2-2.9.2
      command: creates=~/libxml2-2.9.2/Makefile chdir=~/libxml2-2.9.2/ ~/libxml2-2.9.2/configure --libdir=/usr/lib64

    - name: compile and install libxml2-2.9.2
      command: creates=/usr/lib64/libxml2.so.2.9.2 chdir=~/libxml2-2.9.2/ make install

    - name: stop firewall
      command: service iptables stop

    - name: disable firewall service
      command: chkconfig iptables off

    - name: disable selinux
      command: /usr/sbin/setenforce 0


#POSTGRESQL setup
    - name: install postgres repository
      action: command rpm -Uvh --replacepkgs http://yum.postgresql.org/9.2/redhat/rhel-6-x86_64/pgdg-redhat92-9.2-7.noarch.rpm

    - name: install epel
      action: command creates=/etc/yum.repos.d/epel.repo rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

    - name: make sure postgresql packages are installed
      action: yum pkg={{item}} state=installed
      with_items:
        - postgresql92-libs
        - postgresql92-server
        - postgresql92
        - postgis2_92
        - hdf5
        - proj
        - libselinux-python
        - python-psycopg2

    - name: create postgresql cluster
      command: service postgresql-9.2 initdb

    - name: copy all needed postgresql files
      action: copy src={{item}} dest=/{{item}}
      with_items:
        - var/lib/pgsql/9.2/data/postgresql.conf
        - var/lib/pgsql/9.2/data/pg_hba.conf

    - name: starting postgresql service
      command: service postgresql-9.2 start

    - name: enabling postgresql service
      command: chkconfig postgresql-9.2 on

    - name: create geo.gov role
      action: postgresql_user user=geo.gov password=ckan role_attr_flags=SUPERUSER

    - name: create geo role
      action: postgresql_user user=geo password=ckan role_attr_flags=SUPERUSER

    - name: create ckan database
      action: postgresql_db name=ckan owner=geo.gov
    #- name: create ckan database
    #  action: postgresql_db name=ckan owner=geo

    - name: install postgis script
      shell: "psql -d ckan -f /usr/pgsql-9.2/share/contrib/postgis-2.1/postgis.sql"
      sudo: yes
      sudo_user: postgres

    - name: install postgis script
      shell: "psql -d ckan -f /usr/pgsql-9.2/share/contrib/postgis-2.1/spatial_ref_sys.sql"
      sudo: yes
      sudo_user: postgres

    - name: install postgis script
      shell: "psql -d ckan -f /usr/pgsql-9.2/share/contrib/postgis-2.1/rtpostgis.sql"
      sudo: yes
      sudo_user: postgres

    - name: install postgis script
      shell: "psql -d ckan -f /usr/pgsql-9.2/share/contrib/postgis-2.1/topology.sql"
      sudo: yes
      sudo_user: postgres

# After PostgreSQL installation:
# $ gunzip -c /path/to/ckan2_tmp_dump.sql.gz | psql ckan
# $ psql ckan
# ckan=# ANALYZE; 


#CKAN setup
    - name: remove old code
      action: file path=/usr/lib/ckan/src state=absent

    - name: create link of pg_config for postgresql9.2
      action: command ln -sf /usr/pgsql-9.2/bin/pg_config /usr/bin/pg_config

    - name: get ckan version
      action: git repo=https://github.com/GSA/ckan.git dest=/usr/lib/ckan/src/ckan version=release-datagov

    - name: get pip
      action: easy_install name=https://pypi.python.org/packages/source/p/pip/pip-1.3.1.tar.gz

    - name: install requirements and make virtualenv
      action: pip requirements=/usr/lib/ckan/src/ckan/pip-requirements.txt virtualenv=/usr/lib/ckan/ virtualenv_site_packages=yes

    - name: run setup.py develop for ckan
      action: command chdir=/usr/lib/ckan/src/ckan/ ../../bin/python setup.py develop

    - name: make sure pip is 1.3.1
      action: command chdir=/usr/lib/ckan/src/ckan/ ../../bin/easy_install https://pypi.python.org/packages/source/p/pip/pip-1.3.1.tar.gz

    - name: get geodatagov
      action: git repo=https://github.com/mwengren/ckanext-geodatagov dest=/usr/lib/ckan/src/ckanext-geodatagov version=noaa_dev

    - name: get datajson
      action: git repo=https://github.com/18F/ckanext-datajson dest=/usr/lib/ckan/src/ckanext-datajson version=noaa_merge

    - name: get spatial
      action: git repo=https://github.com/18F/ckanext-spatial dest=/usr/lib/ckan/src/ckanext-spatial version=master

    - name: get harvest
      action: git repo=https://github.com/mwengren/ckanext-harvest dest=/usr/lib/ckan/src/ckanext-harvest version=master

    - name: get extra data files
      action: git repo=https://github.com/mwengren/ckanext-geodatagov-extras dest=/usr/lib/ckan/src/ckanext-geodatagov-extras version=master

    - name: install requirements for geodatagov
      action: pip requirements=/usr/lib/ckan/src/ckanext-geodatagov/pip-requirements.txt virtualenv=/usr/lib/ckan/ extra_args='--exists-action i'

    - name: run setup.py develop for geodatagov
      action: command chdir=/usr/lib/ckan/src/ckanext-geodatagov/ ../../bin/python setup.py develop

    - name: install requirements for harvest
      action: pip requirements=/usr/lib/ckan/src/ckanext-harvest/pip-requirements.txt virtualenv=/usr/lib/ckan/ extra_args='--exists-action i'

    - name: install requirements for spatial
      action: pip requirements=/usr/lib/ckan/src/ckanext-spatial/pip-requirements.txt virtualenv=/usr/lib/ckan/ extra_args='--exists-action i'

    - name: install requirements for datajson
      action: pip requirements=/usr/lib/ckan/src/ckanext-datajson/requirements.txt virtualenv=/usr/lib/ckan/ extra_args='--exists-action i'

    - name: run setup.py develop for datajson
      action: command chdir=/usr/lib/ckan/src/ckanext-datajson/ ../../bin/python setup.py develop

    - name: install locations database
      shell: "psql -d ckan -f /usr/lib/ckan/src/ckanext-geodatagov-extras/extras/locations.sql"
      sudo: yes
      sudo_user: postgres

    - name: copy ogc viewer in place 
      shell: "cp /usr/lib/ckan/src/ckanext-geodatagov-extras/extras/viewer.war /var/lib/tomcat6/webapps/ogc_viewer.war"

    - name: set owner of ogc viewer
      shell: "chown tomcat /var/lib/tomcat6/webapps/ogc_viewer.war"

    - name: set permissions of ogc viewer
      shell: "chmod 750 /var/lib/tomcat6/webapps/ogc_viewer.war"

    - name: restarting tomcat service
      action: service name=tomcat6 state=restarted

    - name: remove psycopg2
      action: pip name=psycopg2 virtualenv=/usr/lib/ckan/ state=absent

    - name: install supervisor
      action: pip name=supervisor virtualenv=/usr/lib/ckan/

    - name: remove old repo
      action: file path=/var/www/ckan-repo/master state=absent

    - name: create directories
      action: file path={{item}} state=directory
      with_items:
        - /etc/ckan
        - /var/www/ckan-repo/master

    - name: default apache removed
      action: file path=/etc/httpd/conf.d/welcome.conf state=absent

    - name: copy all needed files
      action: copy src={{item}} dest=/{{item}}
      with_items:
        - etc/ckan/who.ini
        - etc/ckan/apache.wsgi
        - etc/ckan/noaaproduction.ini
        - etc/ckan/production.ini
        - etc/ckan/development.ini
        - etc/supervisord.conf
        - etc/httpd/conf.d/ckan.conf
        - etc/cron.d/ckan-harvest
        - etc/cron.daily/remove_old_sessions
        - etc/init/supervisor.conf
        - var/lib/tomcat6/webapps/fgdc2iso.war

    - name: copy executables
      action: copy src={{item}} dest=/{{item}} mode=744
      with_items:
        - usr/bin/ckan
        - tmp/after_web.sh
        - tmp/after_harvester.sh
        - etc/init.d/ckanless

    - name: create superviserctl symlink
      action: file src=/usr/lib/ckan/bin/supervisorctl dest=/usr/bin/supervisorctl state=link

    - name: restart apache
      action: service name=httpd state=restarted

    - name: packages for web part are installed
      action: yum pkg={{item}} state=installed
      with_items:
        - memcached
        - postgresql92
        - httpd
        - mod_wsgi
        - geos
        - cronie
        - python-psycopg2
        - xmlsec1
        - xmlsec1-openssl
        - swig
        - m2crypto

    - name: make dynamic_menu / do we need this
      shell: "mkdir -p /usr/lib/ckan/src/ckanext-geodatagov/ckanext/geodatagov/dynamic_menu/"

    - name: after web installation script
      action: command /tmp/after_web.sh

    - name: packages for harvester part
      action: yum pkg={{item}} state=installed
      with_items:
        - redis
        - postgresql92
        - geos
        - tomcat6
        - geos
        - cronie
        - python-psycopg2
        - xmlsec1
        - xmlsec1-openssl
        - swig
        - m2crypto
        - java-openjdk
        - libxslt
        - libxml2

    - name: point apache.wsgi to development.ini
      action: command sed -i 's/production.ini/development.ini/g' /etc/ckan/apache.wsgi

    - name: remove default who.ini
      action: file path=/etc/ckan/who.ini state=absent

    - name: download default ckan who.ini
      get_url: url="https://github.com/ckan/ckan/raw/366f1620da29ffaecf7e39d400b5223c8a56417e/ckan/config/who.ini" dest="/etc/ckan/who.ini"

#
# missing Celery?
#
    - name: install Celery
      action: pip name=Celery virtualenv=/usr/lib/ckan/

    - name: get report
      action: git repo=https://github.com/datagovuk/ckanext-report.git dest=/usr/lib/ckan/src/ckanext-report version=master

    - name: run setup.py develop for report
      action: command chdir=/usr/lib/ckan/src/ckanext-report/ ../../bin/python setup.py develop

    - name: get deadoralive
      action: pip name=ckanext-deadoralive virtualenv=/usr/lib/ckan/

#
#  we should swap the production ini in place?
#
    - name: production ini hack
      shell: "mv /etc/ckan/production.ini /etc/ckan/production.ini.bak && ln -s /etc/ckan/noaaproduction.ini /etc/ckan/production.ini"

#
# we probably need to change the permissions on the cache directory
#
    - name: make dynamic_menu / do we need this
      shell: "mkdir -p /usr/lib/ckan/src/ckanext-geodatagov/ckanext/geodatagov/dynamic_menu/"

    - name: fix permissions problem
      shell: "chmod a+rw /usr/lib/ckan/src/ckanext-geodatagov/ckanext/geodatagov/dynamic_menu/"

    - file: path=/usr/lib/ckan/src/ckanext-geodatagov/ckanext/geodatagov/dynamic_menu/menu.json state=touch mode=0666

    - name: Initialize ckan db
      action: command ckan db init

    - name: report initdb
      action: command chdir=/usr/lib/ckan/src/ckanext-report /usr/lib/ckan/bin/paster report initdb --config=/etc/ckan/production.ini

# AJS - not sure why this is a mess
    - name: make dynamic_menu / do we need this
      shell: "mkdir -p /usr/lib/ckan/src/ckanext-geodatagov/ckanext/geodatagov/dynamic_menu/"

    - name: add missing harvest template
      shell: "curl -o /usr/lib/ckan/src/ckan/ckan/templates/snippets/search_form.html https://raw.githubusercontent.com/ckan/ckan/b0ca98a14fce1d4f7f9578723cd9cd3150da5335/ckan/templates/snippets/search_form.html"


#
#  install nodejs and template changes
#

    - name: make sure packages are installed
      action: yum pkg={{item}} state=installed
      with_items:
        - nodejs
        - npm

    - name: install node less
      npm: name=less path=/usr/lib/ckan/src/ckan

    - name: install node nodewatch
      npm: name=nodewatch path=/usr/lib/ckan/src/ckan
 
    - name: enabling node less ckan template service
      command: chkconfig ckanless on

    - name: starting ckanless service
      command: service ckanless start

    - name: after harvester installation script
      action: command /tmp/after_web.sh

    - name: after harvester installation script
      action: command /tmp/after_harvester.sh

# After CKAN installation:
# $ ckan search-index rebuild

#pycsw setup
    - name: get pycsw version
      action: git repo=https://github.com/geopython/pycsw.git dest=/usr/lib/ckan/src/pycsw version=datagov

    - name: run setup build for pycsw
      action: command chdir=/usr/lib/ckan/src/pycsw/ ../../bin/python setup.py build

    - name: run setup install for pycsw
      action: command chdir=/usr/lib/ckan/src/pycsw/ ../../bin/python setup.py install

    - name: install pyproj
      action: pip name=pyproj virtualenv=/usr/lib/ckan/

    - name: install geolinks
      action: pip name=geolinks virtualenv=/usr/lib/ckan/

    - name: copy pycsw configuration files
      action: copy src={{item}} dest=/{{item}} mode=644
      with_items:
        - etc/ckan/pycsw-all.cfg
        - etc/ckan/pycsw-collection.cfg
        - etc/ckan/pycsw.wsgi
        - etc/cron.d/ckan-pycsw
        - usr/lib/ckan/bin/pycsw-db-admin.py
        # - etc/httpd/conf.d/ckan.conf

    - name: create pycsw database
      action: postgresql_db name=pycsw owner=geo.gov

    - name: install postgis for pycsw database
      command: psql -d pycsw -c "CREATE EXTENSION postgis;"
      sudo: yes
      sudo_user: postgres

    - name: create pycsw tables
      action: command chdir=/usr/lib/ckan/src/ckanext-spatial /usr/lib/ckan/bin/paster ckan-pycsw setup -p /etc/ckan/pycsw-all.cfg

    - name: restart apache
      action: service name=httpd state=restarted

    - debug: msg="******************"
    - debug: msg="Next Steps by Hand"
    - debug: msg="******************"
    - debug: msg="copy license saxon-license.lic into /etc/saxon-license.lic"
    - debug: msg="saxon website http://www.saxonica.com/shop/index.html PE version of license"
    - debug: msg="To add all the harvest sources, run the shell script"
    - debug: msg="Create yourself an account"
    - debug: msg="make yourself an admin   ckan sysadmin add <yourusername>"
    - debug: msg="Create a NOAA organization for the harvest sources"
    - debug: msg="national-oceanic-and-atmospheric-administration"
    - debug: msg="/usr/lib/ckan/src/ckanext-geodatagov/deployment/shell_noaa_add_harvest_sources"
